version: '2'
services:
  api:
    build: .
    container_name: api
    command: bash -c "cd /src/rest && pip install celery && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    links:
      - mongo
    volumes:
      - ${ADBREW_CODEBASE_PATH}/tmp:/tmp
      - ${ADBREW_CODEBASE_PATH}:/src

  app:
    build: .
    container_name: app
    command: bash -c "cd /src/app && yarn install && yarn start"
    ports:
      - "3000:3000"
    volumes:
      - ${ADBREW_CODEBASE_PATH}:/src

  mongo:
    image: mongo:4.4
    container_name: mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - ${ADBREW_CODEBASE_PATH}/db/:/data/db
    # sscommand: /usr/bin/mongod --bind_ip 0.0.0.0

    